project_name_override: swmclient
package_name_override: generated
field_prefix: attr_
post_hooks:
   - "autoflake -i -r --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports ."
   - "isort ."
   - "black ."
