name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Prepare virtualenv
        run: |
          rm -rf .venv
          make prepare-venv

      - name: Run static checks
        run: make check

  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Prepare virtualenv
        run: |
          rm -rf .venv
          make prepare-venv

      - name: Run unit tests
        run: make test

